Email verification
BinaryStudioAcademy/bsa-2022-autoline pull request #17
Opened 2022-08-10 18:07 UTC by setar92

1.1 Функція mailSend в backend папка services/mail_verification/send.service.ts повинна бути використана при обробці реєстрації нового користувача. В цю функцію потрібно як аргумент передати email користувача (який є обов'язковим при регістрації).
1.2 Дана ф-я повертає email_activation_token, який потрібно зберегти в таблицю security_user.
1.3 Дана функція, крім того, що створює токен, генерує посилання для підтвердження мейла (токен попадає в закінчення цього посилання) і відправляє повідомлення на мейл користувача (який був переданий, як аргумент).

На backend додано роут "/activate/:link", який буде обробляти валідацію мейла.
Перехід на посилання для активації обробляється наступним чином:
2.1 З силки витягується query "link". Цей лінк має співпадати з email_activation_token в базі даних.
2.2 Шукаємо в базі (табличка user_security) користувача з таким токеном.
2.3 Якщо не знаходемо - редіректимо на роут /mail-failed(цей роут я додав на фронтенд, дизайн сторінки потрібно розробити).
2.4 Якщо знаходимо юзера - значить верифікація успішна. Видаляємо email_activation_token (ставимо йому значення null) і редіректимо юзера на сторінку /mail-saccess (також цей роут додав на фронт).

Щоб перевірити роботу ф-ї mailSend - достатньо викликати її, передавши email як аргумент. Вона відправить посилання на пошту.

2022-08-11 14:24 UTC, RomanMahola requested changes

2022-08-11 14:24 UTC, RomanMahola commented on .env.example/backend.env
> -DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
Did you delete it? Why?

2022-08-11 14:24 UTC, RomanMahola commented on .env.example/frontend.env
> -# API
The same

2022-08-11 14:24 UTC, RomanMahola commented on backend/prisma/schema.prisma
> +  password      String         @db.VarChar(300) // Length of the hashed password
What hash function do you use and why length is 300?

2022-08-11 14:24 UTC, RomanMahola commented on backend/src/common/enums/app/env.enum.ts
> +  MAIL: {
It is not correct.  You should provide params from .env file. 

You also commit smtp password to the public repository. Now anyone can use our mail server.
 Are you crazy?

2022-08-11 14:24 UTC, RomanMahola commented on backend/src/routes/activate/activate.router.ts
> +activateRouter.get('/activate/:link', activate);
Never use verbs in rest api.
This is bad practice

2022-08-11 14:24 UTC, RomanMahola commented on backend/src/server.ts
> +import { healthRouter, authRouter, activateRouter } from '@routes/routes';
activate what? 
subscription? I don`t see what i activate from route. You need to rename it

2022-08-11 14:24 UTC, RomanMahola commented on backend/src/services/mail_verification/send.service.ts
> +    subject: 'Account activation on the website ' + ENV.MAIL.API_URL,
Use "Welcome To AutoLine Community". Don`t provide URL in subject

2022-08-11 14:24 UTC, RomanMahola commented on backend/src/services/mail_verification/send.service.ts
> +    from: ENV.MAIL.SMTP_USER,
I as Administrator want to change mail from autoline.binary@gmail.com to no-reply@autoline.com for specific cases.
Long story short: 
add "from" to function params

2022-08-11 14:24 UTC, RomanMahola commented on backend/src/services/mail_verification/send.service.ts
> +    html: `
Looks dirty 
First, you can provide this HTML to variable, but it is also not good. 
Try to look if it is possible to create HTML template page, for example user_varification.html or any format.
Second, don`t use ${link} twice. links in mails looks ugly. Just make simple text or button would be better

2022-08-11 14:24 UTC, RomanMahola commented on frontend/src/navigation/routing/routing.tsx
> +              <a rel="stylesheet" href="http://localhost:3000/">
You should get site url from configs

2022-08-11 14:24 UTC, RomanMahola commented on frontend/src/navigation/routing/routing.tsx
> +              <a rel="stylesheet" href="http://localhost:3000/sign-up">
same

2022-08-12 16:05 UTC, closed without merging

2022-08-12 16:06 UTC, setar92 commented
I'm going to create new pull request, which include aditional functional and correction according this request warms.