setting-the-carousel-to-detailed-page-layout
BinaryStudioAcademy/bsa-2022-autoline pull request #235
Opened 2022-09-08 08:43 UTC by stanislav-ostr

2022-09-08 17:59 UTC, oleksandr-danylchenko requested changes

2022-09-08 17:59 UTC, oleksandr-danylchenko commented on frontend/src/components/common/carousel/styles.scss
> +    display: block;
C'mon! Why name classes like `mySmth`?

2022-09-08 21:22 UTC, stanislav-ostr commented on frontend/src/components/common/carousel/styles.scss
> +    display: block;
Oops! I will fix this

2022-09-09 06:47 UTC, oleksandr-danylchenko commented on frontend/src/components/common/carousel/carousel.tsx
>  // eslint-disable-next-line @typescript-eslint/no-unused-vars
We don't need this disabled comment anymore

2022-09-09 06:47 UTC, oleksandr-danylchenko submitted a review, later dismissed

2022-09-09 06:56 UTC, merged