setting-the-detailed-car-panel-to-the-detailed-page-layout
BinaryStudioAcademy/bsa-2022-autoline pull request #238
Opened 2022-09-08 09:43 UTC by stanislav-ostr

2022-09-08 18:08 UTC, oleksandr-danylchenko commented
@iryb 
Could you help me out on this PR?

2022-09-08 19:26 UTC, iryb requested changes

2022-09-08 19:26 UTC, iryb commented on frontend/src/components/details-car-panel/details-car-panel.tsx
>    };
@stanislav-ostr It would be better to use `WishlistContext` here like you did in PR #237

2022-09-09 07:05 UTC, iryb approved these changes

2022-09-09 07:06 UTC, merged