Fixed active state of navigation element in site header
BinaryStudioAcademy/bsa-2022-autoline pull request #262
Opened 2022-09-09 22:19 UTC by AlexanderKhapchenko

2022-09-10 11:41 UTC, oleksandr-danylchenko requested changes

2022-09-10 11:41 UTC, oleksandr-danylchenko commented on frontend/src/components/header/header.tsx
> +  const [value, setValue] = useState(-1);
What? What does the `value` mean? Why it's even a `number`?

2022-09-10 11:41 UTC, oleksandr-danylchenko commented on frontend/src/components/header/header.tsx
> +  });
This should be in the `switch` statement as we have comparisons of the static values. What does the numeric value even means? 

To display that smth active we need to store the active route string

2022-09-10 12:05 UTC, iryb commented
I think we need to refactor header menu to use react router dom's `NavLink`. It automatically adds some attributes to anchor tag when it matches the current URL.

2022-09-12 17:28 UTC, oleksandr-danylchenko approved these changes

2022-09-12 17:28 UTC, merged