Notifications update
BinaryStudioAcademy/bsa-2022-autoline pull request #300
Opened 2022-09-13 09:26 UTC by ashonuyak

![image](https://user-images.githubusercontent.com/82455714/189864934-7be27600-4d02-496c-96fb-7877ba9f2f9a.png)

2022-09-13 14:27 UTC, oleksandr-danylchenko commented
@R0ixy @iryb Help me please :pray:

2022-09-13 15:23 UTC, iryb commented
@ashonuyak You should base your PR on https://github.com/BinaryStudioAcademy/bsa-2022-autoline/pull/307 or wait until it will be merged. I can't test it locally.

2022-09-13 15:40 UTC, iryb commented
@ashonuyak Notifications work fine. Please resolve the conflicts.

2022-09-13 16:15 UTC, ashonuyak commented
@iryb done

2022-09-13 16:17 UTC, iryb approved these changes, later dismissed

2022-09-13 16:18 UTC, R0ixy commented on frontend/src/contexts/compare-context.tsx
> +      setNotifications(nextNotifications);
We need to show notification only if user _really_ added car to comparison. Beacuse user can be unauthorized and click on this button. In this case he will be redirected to sign-in but notification still appears.

I think we need to move this logic to `handleAddToCompare`. To RTKQ result promise on line 48

2022-09-13 16:26 UTC, R0ixy requested changes
Please fix this https://github.com/BinaryStudioAcademy/bsa-2022-autoline/pull/300#discussion_r969836321

and I think it can be merged

2022-09-13 17:51 UTC, oleksandr-danylchenko commented
Thanks for pointing this out, @R0ixy :raised_hands:

2022-09-14 11:49 UTC, R0ixy approved these changes
LGTM

2022-09-14 13:15 UTC, oleksandr-danylchenko approved these changes

2022-09-14 13:15 UTC, merged