Email verification
BinaryStudioAcademy/bsa-2022-autoline pull request #31
Opened 2022-08-12 16:15 UTC by setar92

1. Function for sending activating link to user email.
2. Route for verification mail.
3. Route for sending verification link again.

2022-08-13 10:11 UTC, RomanMahola requested changes

2022-08-13 10:11 UTC, RomanMahola commented on README.md
> +3. Run the database. You can either run it in docker using command `cd .docker/autoline && docker-compose -f docker-compose.services.yml up --build` or by installing `Mariadb` on your computer. Docke
Don`t edit README.md

2022-08-13 10:11 UTC, RomanMahola commented on backend/prisma/migrations/20220810085748_user_security/migration.sql
> +-- CreateTable
Drop

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/common/enums/app/route-path.enum.ts
> +  MAIL_ACTIVATE = '/activate/:link',
Don`t use verbs in routes

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/common/enums/app/route-path.enum.ts
> +  MAIL_ACTIVATE_AGAIN = '/again/activate',
delete again 
rename activate for 
user/verififcation
user/verification/:link

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/send_mail_again.ts
> +import { sendMail } from '../../services/mail_verification/send_mail/sendLink';
use @services no ../..

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/send_mail_again.ts
> +
Delete space

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/send_mail_again.ts
> +
Delete space

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/send_mail_again.ts
> +type SendMailAgainBody = {
EmailBody

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/send_mail_again.ts
> +const sendMailAgain = async (
delete again again

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/send_mail_again.ts
> +    const user = await userSecurityService.getUserByEmail(email);
UserService

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/send_mail_again.ts
> +    const token = await sendMail(email);
your function violates single responsibility

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/verification.ts
> +import * as userSecurityService from '@services/mail_verification/user_security.service';
Bad practice

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/send_mail_again.ts
> +import * as userSecurityService from '@services/mail_verification/user_security.service';
Bad pracite

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/verification.ts
> +import { validateMailToken } from '../../services/mail_verification/token.service';
@services

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/verification.ts
> +    const user = await userSecurityService.getByToken(userToken);
Token not unique

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/verification.ts
> +        `${process.env.FRONTEND_URL}${MailActivate.FAILED_URL}`,
check import.meta.env

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/verification.ts
> +        `${process.env.FRONTEND_URL}${MailActivate.FAILED_URL}`,
check import.meta.env

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/controllers/mail_varification/verification.ts
> +      `${process.env.FRONTEND_URL}${MailActivate.SUCCESS_URL}`,
add to const

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/routes/auth/auth.router.ts
> +authRouter.post(`${PATH}/local/signup`, authController.signupLocal);
why local

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/services/mail_verification/send_mail/constants.ts
> +  FAILED_URL: '/mail-activate-failed',
`
varification-success
varification-failed
`

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/services/mail_verification/send_mail/constants.ts
> +  ACTIVATE_URL: 'localhost:3001/api/v1/activate/',
LOCALHOST??????

**USE APP URL**

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/services/mail_verification/send_mail/sendLink.ts
> +    port: 587,
add to const

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/services/mail_verification/send_mail/sendLink.ts
> +      isMailtrap: true,
Delete

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/services/mail_verification/send_mail/sendLink.ts
> +      message: 'Incorrect email',
err.message

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/services/mail_verification/send_mail/sendLink.ts
> +  return token;
SIngle responsibility

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/services/mail_verification/send_mail/templates/send_verification_link.ts
> +  return `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
try to use template

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/services/mail_verification/token.service.ts
> +function validateMailToken(token: string): string | boolean {
Is it good to return string | boolean

2022-08-13 10:11 UTC, RomanMahola commented on backend/src/services/mail_verification/user_security.service.ts
> +const getUserByEmail = async (email: string): Promise<Prisma.User | null> => {
provide to User Service

2022-08-13 10:11 UTC, RomanMahola commented on frontend/src/common/enums/app/links.enum.ts
> +  SIGN_IN = 'http://localhost:3000/sign-in',
change localhost:3000

2022-08-13 10:11 UTC, RomanMahola commented on frontend/src/components/top-car-card/styles.module.scss
> +.container {
Delete this file from this PR

2022-08-13 10:11 UTC, RomanMahola commented on frontend/src/components/top-car-card/styles.module.scss
> +  font-family: Lato, sans-serif;
use variables

2022-08-13 10:11 UTC, RomanMahola commented on frontend/src/components/top-car-card/top-car-card.tsx
> +import { FC } from 'react';
Delete this file from PR

2022-08-13 10:11 UTC, RomanMahola commented on yarn.lock
> -  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.18.6.tgz#3b25d38c89600baa2dcc219edfa88a74eb2c427a"
check

2022-08-13 17:42 UTC, setar92 commented on backend/src/controllers/mail_varification/verification.ts
> +        `${process.env.FRONTEND_URL}${MailActivate.FAILED_URL}`,
don't work on backend

2022-08-13 17:42 UTC, setar92 commented on backend/src/controllers/mail_varification/verification.ts
> +        `${process.env.FRONTEND_URL}${MailActivate.FAILED_URL}`,
don't work on backend

2022-08-13 19:04 UTC, setar92 commented on yarn.lock
> -  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.18.6.tgz#3b25d38c89600baa2dcc219edfa88a74eb2c427a"
My mistake, used "npx prisma migrate" instead "npx prisma migrate"

2022-08-14 16:33 UTC, setar92 commented on backend/src/services/mail_verification/send_mail/templates/send_verification_link.ts
> +  return `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
done

2022-08-17 11:50 UTC, nikita-remeslov approved these changes, later dismissed
Looks good to me. 1 minor remark needs to be fixed

2022-08-17 11:50 UTC, nikita-remeslov commented on frontend/src/navigation/routing/routing.tsx
> +
redundant indent

2022-08-17 12:13 UTC, nikita-remeslov approved these changes

2022-08-17 12:24 UTC, merged