Front mail verification
BinaryStudioAcademy/bsa-2022-autoline pull request #36
Opened 2022-08-15 20:33 UTC by setar92

Created verification failed and saccess pages. 
https://gyazo.com/b84cac72da5c32356c53e2491de3d37c
https://gyazo.com/23bdb345f3fa45db90d387ffd9641c48

2022-08-16 20:14 UTC, oleksandr-danylchenko requested changes
Some polishing would be appreaciated

2022-08-16 20:14 UTC, oleksandr-danylchenko commented on frontend/src/components/mail-verification/verification-failed/failed.tsx
> +  const [email, setEmail] = useState({ email: '' });
Why do you use the object in the state?

2022-08-16 20:14 UTC, oleksandr-danylchenko commented on frontend/src/components/mail-verification/verification-failed/failed.tsx
> +  const [requestLink] = emailApi.useRequestLinkMutation();
Usually, only the hooks are exported, not the whole api object

2022-08-16 20:14 UTC, oleksandr-danylchenko commented on frontend/src/components/mail-verification/verification-failed/failed.tsx
> +  };
`camelCase` naming should be preserved. Therefore you should use the `onChangeHandler`. Although, why do you use the object for the email? :thinking:

2022-08-16 20:14 UTC, oleksandr-danylchenko commented on frontend/src/components/mail-verification/verification-success/styles.module.scss
> +}
These styles should be broght to some higher level and reused. Because I see that they are duplicafted

2022-08-16 20:14 UTC, oleksandr-danylchenko commented on frontend/src/services/request-verification-link/email-link-service.ts
> +export { emailApi };
Please follow the one-root-createApi that @o-rudych shared here - https://binary-academy-2022.slack.com/archives/C03SA9P93C6/p1660658147966669

2022-08-17 18:52 UTC, nikita-remeslov requested changes
In general, looks good, but we have a big problem with styling. We should define the default style variable to use in the whole project

2022-08-17 18:52 UTC, nikita-remeslov commented on frontend/src/assets/css/wrapper.scss
> +@media (max-width: 641px) {
Why do we use such a breakpoint? 

We should have global variables for breakpoint

2022-08-17 18:52 UTC, nikita-remeslov commented on frontend/src/components/mail-verification/verification-success/styles.module.scss
> +@media (max-width: 641px) {
Used 2 times. I already want to create a variable :)

2022-08-22 19:06 UTC, oleksandr-danylchenko approved these changes, later dismissed
Just minor suggestions

2022-08-22 19:06 UTC, oleksandr-danylchenko commented on frontend/src/assets/css/wrapper.scss
> +}
Please use SCSS nesting

```suggestion
.bgImage {
  position: relative;
  z-index: 1;
  display: flex;
  align-items: center;
  min-height: 100vh;
  background-position: center center;
  background-size: cover;

  &::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    z-index: -1;
    width: 100%;
    height: 100%;
    background-color: var(--blue300);
    opacity: 0.5;
  }
}
```

2022-08-22 19:06 UTC, oleksandr-danylchenko commented on frontend/src/components/mail-verification/verification-failed/failed.tsx
> +const Failed: FC = (): React.ReactElement => {
`Failed` -> `EmailVerificationFailed`

2022-08-22 19:06 UTC, oleksandr-danylchenko commented on frontend/src/components/mail-verification/verification-success/success.tsx
> +const Success: FC = (): React.ReactElement => {
`Success` -> `EmailVerificationSucess`

2022-08-22 19:11 UTC, oleksandr-danylchenko commented on frontend/src/components/mail-verification/verification-success/success.tsx
> +const Success: FC = (): React.ReactElement => {
### **Also, **_very important_**, the React components files are named from the capital letter!**

2022-08-22 19:16 UTC, merged