Connect sign in form with backend
BinaryStudioAcademy/bsa-2022-autoline pull request #37
Opened 2022-08-16 16:01 UTC by brovarenko

See - https://app.asana.com/0/1202525679663009/1202782033632767/f

2022-08-16 20:27 UTC, oleksandr-danylchenko requested changes
Some polishing would be appreciated

2022-08-16 20:27 UTC, oleksandr-danylchenko commented on frontend/src/common/types/form/form-control-values.type.ts
> +export { type FormControlValues };
Why did you reexport this type and didn't use the `'react-hook-form`'s one?

2022-08-16 20:27 UTC, oleksandr-danylchenko commented on frontend/src/common/types/form/form-control-path.type.ts
> +export { type FormControlPath };
Why did you make this custom type?

2022-08-16 20:27 UTC, oleksandr-danylchenko commented on frontend/src/common/types/form/form-control-errors.type.ts
> +export { type FormControlErrors };
Why it's reexported?

2022-08-16 20:27 UTC, oleksandr-danylchenko commented on frontend/src/common/types/form/form-control.type.ts
> +export { type FormControl };
Why reexport?

2022-08-16 20:27 UTC, oleksandr-danylchenko commented on frontend/src/components/common/input-field/input-field.tsx
> +}: InputFieldPropsType): React.ReactElement => {
Please use the `React`'s `FC` type for the components declaration:

```jsx
interface SomeProps { foo: boolean };
const  SomeComponent: FC<SomeProps> = ({ foo }) => {...}
```

2022-08-16 20:27 UTC, oleksandr-danylchenko commented on frontend/src/helpers/validation/get-form-validation-resolver.ts
> +};
```suggestion
const getFormValidationResolver = (
  validationSchema: ValidationSchema<object>,
): Resolver => yupResolver(validationSchema);
```

2022-08-16 20:27 UTC, oleksandr-danylchenko commented on frontend/src/store/queries/index.ts
> +export const Api = createApi({
We should use the names that start in uppercase. The `camelCase` is the standard

2022-08-16 20:27 UTC, oleksandr-danylchenko commented on shared/src/common/types/validation/validation-schema.type.ts
> +export { type SchemaOf as ValidationSchema } from 'yup';
Why reexport?

2022-08-17 17:36 UTC, nikita-remeslov approved these changes, later dismissed
Looks good to me.
PS. Please resolve conflicts

2022-08-17 17:37 UTC, oleksandr-danylchenko submitted a review, later dismissed

2022-08-19 10:33 UTC, oleksandr-danylchenko commented on frontend/yarn.lock
> +>>>>>>> develop
```suggestion
react-hook-form@^7.34.2:
  version "7.34.2"
  resolved "https://registry.yarnpkg.com/react-hook-form/-/react-hook-form-7.34.2.tgz#9ac6d1a309a7c4aaa369d1269357a70e9e9bf4de"
  integrity sha512-1lYWbEqr0GW7HHUjMScXMidGvV0BE2RJV3ap2BL7G0EJirkqpccTaawbsvBO8GZaB3JjCeFBEbnEWI1P8ZoLRQ==
```

2022-08-19 10:44 UTC, oleksandr-danylchenko approved these changes

2022-08-19 10:44 UTC, merged