corrected template for verification mail message
BinaryStudioAcademy/bsa-2022-autoline pull request #55
Opened 2022-08-21 13:49 UTC by setar92

https://gyazo.com/7f062e6988fca90c1a44632c0b85564a

2022-08-21 17:50 UTC, oleksandr-danylchenko requested changes

2022-08-21 17:50 UTC, oleksandr-danylchenko commented on backend/src/services/mail-verification/send-activation-link/templates/email.hbs
> +              style="text-decoration:none; background-color: #3765FF; border: #032081 1px solid; color: #fff; padding:10px 10px; display:block;"
Could you please round the corners?

2022-08-21 17:50 UTC, oleksandr-danylchenko commented on backend/src/services/mail-verification/send-activation-link/templates/email.hbs
> +<body style="background-color: #ffffff; font-size: 16px;">
Could we use a different, more modern, sans-serif font for the email?

2022-08-22 11:28 UTC, setar92 commented
https://gyazo.com/9857ec466bc59cd65c29ff76d78a3a89

2022-08-22 20:20 UTC, oleksandr-danylchenko approved these changes

2022-08-22 20:20 UTC, merged