Header wishlist integration
BinaryStudioAcademy/bsa-2022-autoline pull request #61
Opened 2022-08-22 19:24 UTC by iryb

Task https://app.asana.com/0/1202525679663009/1202720801120417

## One model in wishlist:
![wishlist-header](https://user-images.githubusercontent.com/44324806/186001927-c476cc62-45a6-4c1a-8ccc-24a279616534.jpg)

## Empty wishlist
![wishlist-0-header](https://user-images.githubusercontent.com/44324806/186002016-12641ad1-555b-4524-86ac-2ce5ff18a571.jpg)

2022-08-22 20:30 UTC, oleksandr-danylchenko commented
We mustn't show empty lists like that: 
![image](https://user-images.githubusercontent.com/68850090/186013018-800cae9e-9167-4b2c-84e4-fd270c1e1472.png)
I should be either the explicit message: "Nothing is in wishlist" or the emptiness

2022-08-22 20:32 UTC, oleksandr-danylchenko commented
Please choose the branch from which you started the current one as the merge target. In this way, the change diff will be much smaller

2022-08-22 20:34 UTC, oleksandr-danylchenko requested changes

2022-08-22 20:34 UTC, oleksandr-danylchenko commented on frontend/src/components/header/header.tsx
> +    favorites: wishlist?.count as number | 0,
`|` here is not what you expect :sweat_smile: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_OR

2022-08-23 05:19 UTC, iryb commented
> We mustn't show empty lists like that: ![image](https://user-images.githubusercontent.com/68850090/186013018-800cae9e-9167-4b2c-84e4-fd270c1e1472.png) It should be either emptiness or an explicit message like "Nothing is in wishlist". I would prefer to the latter

### If nothing is in favorites:
![image](https://user-images.githubusercontent.com/44324806/186075843-5581145a-46f4-4a28-b861-45388a56a7b0.png)

2022-08-23 18:23 UTC, oleksandr-danylchenko requested changes

2022-08-23 18:23 UTC, oleksandr-danylchenko commented on backend/src/services/preferences/wishlist.service.ts
>    };
I would put the counting login on the client side. Then we'll be able to update the liked count right after the like

2022-08-23 18:23 UTC, oleksandr-danylchenko commented on frontend/src/components/header/header.tsx
> +    favorites: wishlist && wishlist.count,
We shouldn't use `smth &&` check in the modern JS. There a optional [chaining operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) in JS to work with possibly `undefined` objects

2022-08-23 18:23 UTC, oleksandr-danylchenko commented on shared/src/common/types/preferences/wishlist-response-dto.type.ts
> +  count: number;
`count` would better live on the client

2022-08-24 17:04 UTC, oleksandr-danylchenko approved these changes

2022-08-24 17:04 UTC, merged