Add Complete Set component
BinaryStudioAcademy/bsa-2022-autoline pull request #66
Opened 2022-08-23 16:32 UTC by iryb

Task https://app.asana.com/0/1202525679663009/1202838302178341

![complete-set-table](https://user-images.githubusercontent.com/44324806/186212412-d3bb9d64-816c-44d6-881f-05dc68354a36.gif)

2022-08-23 16:36 UTC, iryb commented
What do you think about white color box? I styled it as in mockup but the border is almost invisible on un-hover table row. Do you want to leave it as it is now or apply darker border?

2022-08-23 18:00 UTC, oleksandr-danylchenko commented
> What do you think about white color box?

It should be framed into the `box-shadow`. The result can look smth like this - https://playcode.io/946847/

2022-08-23 18:11 UTC, oleksandr-danylchenko requested changes
- The colors boxes should be framed into the `box-shadow`
- We mustn't use objects instead of the `enum`s in TS

2022-08-23 18:11 UTC, oleksandr-danylchenko commented on frontend/src/common/enums/car/options.enum.ts
> +export { CarSetOptions };
This is not `enum`. Why it's located in the `enum` file? :eyes:

2022-08-23 18:11 UTC, oleksandr-danylchenko commented on frontend/src/components/complete-set-table/complete-set-table.tsx
> +                ></div>
`div` can be collapsed: 
```suggestion
                <div
                  className={styles.colorBox}
                  style={{ backgroundColor: car.color }}
                />
```

2022-08-23 18:29 UTC, iryb commented on frontend/src/common/enums/car/options.enum.ts
> +export { CarSetOptions };
You are totally right. Thank you!

2022-08-24 07:41 UTC, oleksandr-danylchenko approved these changes

2022-08-24 07:41 UTC, merged