add cities endpoint
BinaryStudioAcademy/bsa-2022-autoline pull request #92
Opened 2022-08-25 18:19 UTC by R0ixy

2022-08-25 18:25 UTC, oleksandr-danylchenko requested changes

2022-08-25 18:25 UTC, oleksandr-danylchenko commented on backend/src/controllers/cars/cars.controller.ts
> +    const models = await carsService.getCities(req.params.id);
Cities are not part of the `car`'s ecosystem. They should be handled in a separate service

2022-08-25 18:25 UTC, oleksandr-danylchenko commented on backend/src/services/cars/cars.service.ts
> +};
**Don't use return await in async functions!**

https://kanby.medium.com/%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-return-await-%D0%BF%D0%BB%D0%BE%D1%85%D0%B0%D1%8F-%D0%B8%D0%B4%D0%B5%D1%8F-e87b70015f0c

2022-08-25 18:27 UTC, R0ixy commented on backend/src/controllers/cars/cars.controller.ts
> +    const models = await carsService.getCities(req.params.id);
Well, but we handle regions in the cars service. This functionality was implemented eartier, I'm just adding some missing parts

2022-08-25 18:36 UTC, oleksandr-danylchenko commented on backend/src/controllers/cars/cars.controller.ts
> +    const models = await carsService.getCities(req.params.id);
Oh-oh. Then it somehow slipped through my attention. Could you please create a separate service for the locations?

2022-08-26 06:10 UTC, oleksandr-danylchenko approved these changes

2022-08-26 06:10 UTC, merged