History of viewed cars connected back with front
BinaryStudioAcademy/bsa-2022-autoline pull request #95
Opened 2022-08-25 19:47 UTC by Aleksandr-Shulha-dev

General view of the component on the page: 
![image](https://user-images.githubusercontent.com/62075764/186754467-faec14ad-d5d6-4d7b-8fcd-4d1f4ae94f5e.png)
https://gyazo.com/47b5aa304f162ec3927819c5eaa7cef6

2022-08-26 10:52 UTC, Aleksandr-Shulha-dev commented
Pagination data: https://gyazo.com/47b5aa304f162ec3927819c5eaa7cef6

2022-08-26 16:56 UTC, Aleksandr-Shulha-dev commented
I'm sorry about a large number of modified files. When i was creating the client`s side and the server side, I did not take into account many details (the dark side filled my mind 👾). And when I understood it, it was too late( It was the last time, I promise.

2022-08-28 18:14 UTC, oleksandr-danylchenko commented
@Aleksandr-Shulha-dev 
Why did you use the centering of the card labels? In design, we use left aligning
![image](https://user-images.githubusercontent.com/68850090/187088665-892eb59c-dec0-4fc9-b2a6-e70e65d7baab.png)

2022-08-28 18:15 UTC, oleksandr-danylchenko commented
> 

I don't understand what happens in the video :eye
Do you load the new cars on "View more"?

2022-08-28 18:16 UTC, oleksandr-danylchenko commented
Why there are 2 cars with same model+complectation combination on the page?

2022-08-28 18:17 UTC, oleksandr-danylchenko commented
> Pagination data: https://gyazo.com/47b5aa304f162ec3927819c5eaa7cef6

I don't understand what happens in the video :eye
Do you load the new cars on "View more"?

2022-08-28 18:17 UTC, oleksandr-danylchenko commented
> I'm sorry about a large number of modified files. When i was creating the client`s side and the server side, I did not take into account many details (the dark side filled my mind space_invader). And when I understood it, it was too late( It was the last time, I promise.

It's never late to create 2 new branches and cherry pick changes to them separately

2022-08-28 18:19 UTC, oleksandr-danylchenko commented on backend/src/helpers/viewed-cars/viewed-cars.ts
> +    : String(data.year_start),
The `${data.year_start}` would be preferred more than the `String` constuctor

2022-08-28 18:26 UTC, oleksandr-danylchenko requested changes
The infinity scroll concept or the pagination won't work here bc on each request we'll get the already fetched data in the response

2022-08-28 18:26 UTC, oleksandr-danylchenko commented on frontend/src/components/viewed-cars/viewed-cars.tsx
> +  };
`useGetHistoryOfViwedCarsQuery` would perform the requests which will contain the already downloaded cars. So the pagination concept isn't really working here

2022-08-28 18:26 UTC, oleksandr-danylchenko commented on frontend/src/components/viewed-cars/viewed-cars.tsx
> +  };
This object will be recreated on each rerender and the `useGetHistoryOfViwedCarsQuery` will be restarted on each rerender as well

2022-08-29 06:28 UTC, Aleksandr-Shulha-dev commented
> @Aleksandr-Shulha-dev Why did you use the centering of the card labels? In design, we use left aligning ![image](https://user-images.githubusercontent.com/68850090/187088665-892eb59c-dec0-4fc9-b2a6-e70e65d7baab.png)

In order for the button "load more" was in the center
![image](https://user-images.githubusercontent.com/62075764/187136928-d92827a8-fc56-4bb2-a9bf-a06033435220.png)

2022-08-29 06:41 UTC, oleksandr-danylchenko commented
> In order for the button "load more" was in the center ![image](https://user-images.githubusercontent.com/62075764/187136928-d92827a8-fc56-4bb2-a9bf-a06033435220.png)

Not sure how the centering of the container element should impact the cards. This should be fixed and the centering should be applied only the `Load more` button

2022-08-29 07:19 UTC, Aleksandr-Shulha-dev commented
> Why there are 2 cars with the same model+complectation combination on the page? ![image](https://user-images.githubusercontent.com/68850090/187088731-7eefa30a-8bca-4726-83b5-90a93a1abfe5.png)

In the database we have a lot of identical cars with different id. And I used old data. Now it's looks like this. 
![image](https://user-images.githubusercontent.com/62075764/187145381-fb10b014-f76f-442b-9869-b04ea55d4fdd.png)

2022-08-29 07:32 UTC, Aleksandr-Shulha-dev commented
> @Aleksandr-Shulha-dev Why did you use the centering of the card labels? In design, we use left aligning ![image](https://user-images.githubusercontent.com/68850090/187088665-892eb59c-dec0-4fc9-b2a6-e70e65d7baab.png)



> Why there are 2 cars with the same model+complectation combination on the page? ![image](https://user-images.githubusercontent.com/68850090/187088731-7eefa30a-8bca-4726-83b5-90a93a1abfe5.png)



> Why there are 2 cars with the same model+complectation combination on the page? ![image](https://user-images.githubusercontent.com/68850090/187088731-7eefa30a-8bca-4726-83b5-90a93a1abfe5.png)



> > Pagination data: https://gyazo.com/47b5aa304f162ec3927819c5eaa7cef6
> 
> I don't understand what happens in the video :eye Do you load the new cars on "View more"?


I mistakenly added another video.

https://gyazo.com/a7528e611f1cb3a09c1da5b679d7eff4

2022-08-31 14:23 UTC, Aleksandr-Shulha-dev commented
![image](https://user-images.githubusercontent.com/62075764/187702369-0e312571-e963-4831-93c1-bb902cd7c503.png)

2022-08-31 16:51 UTC, oleksandr-danylchenko approved these changes

2022-08-31 16:53 UTC, merged